apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: NodePort
  ports:
    - port: 3000
      name: app
      nodePort: 32100
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        # Because kube-registry-proxy is present localhost access is via http instead of https
        image: registry.hub.docker.com/taroball/taro1
        ports:
        - containerPort: 3000